version: '3.6'

#create a overlay network called 'consul-net' before deploying the stack 
networks:
  consul-net:
    external: true

services:
  vault:
    image: vault:latest
    hostname: vault
    labels: [app=vault]
    ports:
      - "8200:8200"
      - "8201:8201"
    networks:
        - consul-net
    volumes:
      - ./config:/vault/config
      - ./policies:/vault/policies
      - ../vault-data:/vault/data
      - ../logs:/vault/logs
      - ./tools/:/tools/
    environment:
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_CLUSTER_ADDR=http://127.0.0.1:8201
    entrypoint: /tools/wait-for-it.sh -t 50 -h consul -p 8500 -s -- vault server  -config=/vault/config/vault-config.json
    depends_on:
      - consul
    deploy:
      mode: global
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      update_config:
          parallelism: 1
          delay: 10s
          failure_action: continue
      endpoint_mode: vip
 
  consul:
    image: sdelrio/consul${TAG}
    labels: [app=consul]
    ports:
      - "8500:8500"
    networks:
      - consul-net
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true,  "log_level": "DEBUG",  "server": true,  "ui": true}'
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL=consul
      - CONSUL_CHECK_LEADER=true
    deploy:
      mode: global
      resources:
          reservations:
              memory: 128M
      restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      update_config:
          parallelism: 1
          delay: 10s
          failure_action: continue
      endpoint_mode: vip

